# Sample config file for toolkit upload
# toolkit-upload-config.yaml
general:
  retries: 3
  timeout: 30
  verbose: true
  insecure: true
app:
  base_url: "<https://concert_url:concert_port>"
  instance_id: "<your_instance_id>"
  auth:
    user:
      username: "<your_username>"
      password: "<your_password>"
  # TODO: certs
input-data:
  build:
    files:
    - "/toolkit-data/concert-sample-1-built-assets.json"
  cyclonedx:
    files:
    - "/toolkit-data/concert-sample-1-cyclonedx-sbom.json"

